package com.igormaznitsa.jhexed.swing.editor.ui.dialogs;

public class DialogAbout extends javax.swing.JDialog {
  private static final long serialVersionUID = -8850290336144697768L;

  public DialogAbout(java.awt.Frame parent) {
    super(parent, true);
    initComponents();
    pack();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonClose = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jXLabel1 = new org.jdesktop.swingx.JXLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("About");
    setLocationByPlatform(true);

    buttonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/igormaznitsa/jhexed/swing/editor/icons/cross.png"))); // NOI18N
    buttonClose.setText("Close");
    buttonClose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonCloseActionPerformed(evt);
      }
    });

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/igormaznitsa/jhexed/swing/editor/icons/logo.png"))); // NOI18N

    jXLabel1.setText("<html><body>\n<h2>JHexed Map Editor</h2> \n<p>Author: igor Maznitsa (<a href=\"http://www.igormaznitsa.com\">http://www.igormaznitsa.com</b>)</p>\n<hr>\n <p>The Utility allows to edit multilevel hexagonal maps with SVG icons and background. For work with SVG images it uses the SVG Salamander framework, for work with hexagons it uses JHexed framework.</p>   \n<hr>\n<h3>Licenses</h3>\n<ul>\n<li>JHexed framework: Apache License 2.0 (<a href=\"https://code.google.com/p/jhexed/\">https://code.google.com/p/jhexed/</a>) </li>\n<li>SVG Salamander framework: LGPL and BSD (<a href=\"https://svgsalamander.java.net/\">https://svgsalamander.java.net/</a>)</li>\n<li>SwingX framework: LGPL (<a href=\"https://swingx.java.net//\">https://swingx.java.net/</a>)</li>\n<li>Fugue Icons: CCA 3.0 License (<a href=\"http://p.yusukekamiyamane.com/\">http://p.yusukekamiyamane.com/</a>)</li>\n<li>Free Vintage Design Icons: CCA 3.0 License (<a href=\"http://www.designcontest.com/free-icons/\">http://www.designcontest.com/free-icons/</a>)</li>\n</ul>\n</body></html>");
    jXLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jXLabel1.setLineWrap(true);
    jXLabel1.setPreferredSize(new java.awt.Dimension(450, 12));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(buttonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jXLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jXLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(buttonClose)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
    dispose();
  }//GEN-LAST:event_buttonCloseActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonClose;
  private javax.swing.JLabel jLabel1;
  private org.jdesktop.swingx.JXLabel jXLabel1;
  // End of variables declaration//GEN-END:variables
}
